# 氨基酸偏好设置（改善可溶性）
pdb_path: mpnn/data/monomers/5L33.pdb
out_folder: mpnn/outputs/06_bias_aa
bias_AA: "D:2.0,E:2.0,K:2.0,R:2.0,N:1.5,Q:1.5,S:1.5,T:1.5,W:-2.0,F:-2.0,I:-1.5,L:-1.5"
batch_size: 5
number_of_batches: 2
temperature: 0.1
seed: 42
