# 残基级氨基酸偏好
pdb_path: mpnn/data/with_dna/1BC8.pdb
out_folder: mpnn/outputs/11_per_residue_bias
chains_to_design: "C"
bias_AA_per_residue: mpnn/data/configs/bias_AA_per_residue.json
batch_size: 5
number_of_batches: 2
temperature: 0.1
seed: 42
